# Generated by Django 5.0.4 on 2025-05-20 11:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPAP', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profiles',
            field=models.ManyToManyField(to='appPAP.profile'),
        ),
        migrations.AddField(
            model_name='movie',
            name='age_limit',
            field=models.CharField(blank=True, choices=[('All', 'Adultos'), ('Kids', 'Kids')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='age_limit',
            field=models.CharField(choices=[('All', 'Adultos'), ('Kids', 'Kids')], default='All', max_length=15),
        ),
        migrations.AlterField(
            model_name='movie',
            name='type',
            field=models.CharField(choices=[('Documentário', 'Documentário'), ('Biografia', 'Biografia'), ('Histórico', 'Histórico'), ('Ciência e Natureza', 'Ciência e Natureza'), ('Educativo', 'Educativo'), ('Literário', 'Literário')], max_length=20),
        ),
        migrations.AlterField(
            model_name='movie',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_profiles', to='appPAP.movie'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='watch_later',
            field=models.ManyToManyField(blank=True, related_name='watch_later_profiles', to='appPAP.movie'),
        ),
    ]
