# Generated by Django 5.0.4 on 2025-05-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPAP', '0002_alter_customuser_options_alter_movie_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Regular', 'Professor')], default='Regular', max_length=15),
        ),
    ]
