# Generated by Django 5.0.4 on 2025-05-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPAP', '0003_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='admin_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
