# Generated by Django 5.0.4 on 2025-05-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPAP', '0004_profile_admin_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age_limit',
            field=models.CharField(choices=[('All', 'Adultos'), ('Kids', 'Kids')], default='All', max_length=15, null=True),
        ),
    ]
