# Generated by Django 5.0.4 on 2025-05-22 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPAP', '0005_alter_profile_age_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age_limit',
        ),
    ]
