# Generated by Django 5.0.4 on 2025-05-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPAP', '0006_remove_profile_age_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age_limit',
            field=models.CharField(choices=[('All', 'All'), ('Kids', 'Kids')], default='All', max_length=15),
        ),
        migrations.AlterField(
            model_name='movie',
            name='age_limit',
            field=models.CharField(choices=[('All', 'All'), ('Kids', 'Kids')], default='All', max_length=15),
        ),
    ]
