# Generated by Django 5.0.4 on 2025-05-26 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPAP', '0008_alter_movie_age_limit_alter_profile_age_limit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='admin_password',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profiles',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='age_limit',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='age_limit',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL),
            preserve_default='True',
        ),
    ]
