# Generated by Django 5.0.4 on 2025-06-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPAP', '0010_alter_profile_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Regular', 'Professor'), ('Coordenador', 'Coordenador')], default='Regular', max_length=15),
        ),
    ]
