# Generated by Django 5.0.4 on 2025-06-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPAP', '0012_profile_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='banner',
            field=models.ImageField(default='banners/defaultbanner.jpg', upload_to='banners'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_picture',
            field=models.ImageField(blank=True, default='profile_pictures/avatardefault.jpg', null=True, upload_to='profile_pictures'),
        ),
    ]
