# Generated by Django 5.0.4 on 2025-06-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPAP', '0013_movie_banner_profile_user_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.FileField(blank=True, default='trailers/defaulttrailer.mp4', null=True, upload_to='trailers'),
        ),
    ]
