# Generated by Django 5.0.4 on 2025-06-30 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPAP', '0015_category_alter_profile_password_alter_movie_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='trailer',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_picture',
        ),
    ]
